fix test framework dependencies
UiPath-TAM-Team/UiPathTAMTeam.Extensions.Activities pull request #6
Opened 2023-06-21 20:08 UTC by mkuehn10

2023-06-21 20:24 UTC, k2zinger requested changes
Can you review these items and resubmit please?

2023-06-21 20:24 UTC, k2zinger commented on UiPathTeam.Extensions.Tests/UiPathTeam.Extensions.Tests.csproj
> +    <PackageReference Include="MSTest.TestAdapter" Version="2.2.10" />
Upgrade to newer version?
https://www.nuget.org/packages/MSTest.TestAdapter/3.0.4

2023-06-21 20:24 UTC, k2zinger commented on UiPathTeam.Extensions.Tests/UiPathTeam.Extensions.Tests.csproj
> +    <PackageReference Include="MSTest.TestFramework" Version="2.2.10" />
Upgrade to a newer version?
https://www.nuget.org/packages/MSTest.TestFramework/3.0.4

2023-06-21 20:24 UTC, k2zinger commented on UiPathTeam.Extensions.Tests/UiPathTeam.Extensions.Tests.csproj
> +    <PackageReference Include="coverlet.collector" Version="3.2.0" />
Upgrade to a newer version?
https://www.nuget.org/packages/coverlet.collector/6.0.0

2023-06-21 22:07 UTC, mkuehn10 commented
Changes made @k2zinger

2023-06-22 00:29 UTC, k2zinger approved these changes

2023-06-22 00:30 UTC, merged