Clear Dictionary Activity
UiPath-TAM-Team/UiPathTAMTeam.Extensions.Activities pull request #67
Opened 2023-10-10 22:03 UTC by sebR18

Lets try this again

2023-10-11 13:00 UTC, k2zinger requested changes
additional changes requested

2023-10-11 13:00 UTC, k2zinger commented on UiPathTeam.Extensions/UiPathTeam.Extensions.Activities/Properties/Resources.resx
> +  <data name="Authentication_Category" xml:space="preserve">
remove multiple duplicates, leave the first entry earlier in the file

e.g.
lines 148-151 and 372-375, remove the section for 372-375 (duplicate)

2023-10-23 18:01 UTC, k2zinger commented on .gitignore
> +/UiPathTeam.Extensions/UiPathTeam.Extensions.Activities.Design/Themes/Icons.xaml
ignoring this file means it is ignored from this point forward, so any valid changes to this file would be ignored
ignored files are typically files that are generated when user opens a project in Visual Studio / UiPath Studio and those files are not required to open the project on someone else's machine - this is especially important for temporary files

2023-10-23 20:44 UTC, sebR18 commented on .gitignore
> +/UiPathTeam.Extensions/UiPathTeam.Extensions.Activities.Design/Themes/Icons.xaml
removed the file from .gitignore

2023-10-23 22:56 UTC, k2zinger approved these changes

2023-10-23 22:56 UTC, merged